---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sfmc-new-flux-service
  namespace: flux-system
spec:
  provider: aws # Automatic authentication if the IAM role is allowed to read from ECR
  image: 860234270284.dkr.ecr.eu-west-1.amazonaws.com/sfmc-new-flux-service # Prod ECR repsitory
  interval: 1m0s